"""empty message

Revision ID: 01dd88a9ed3d
Revises: 929bf4ad2559
Create Date: 2019-03-22 23:08:50.439228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01dd88a9ed3d'
down_revision = '929bf4ad2559'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maps', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'maps', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'maps', type_='foreignkey')
    op.drop_column('maps', 'user_id')
    # ### end Alembic commands ###
