"""empty message

Revision ID: 2b0e3721e747
Revises: 
Create Date: 2019-04-02 20:44:26.165872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b0e3721e747'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('maps_user_id_fkey', 'maps', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('maps_user_id_fkey', 'maps', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
